[TOC]

`Java`可以被抛出的异常或错误都继承自`throwable`类。

语法错误不属于异常，在运行时出现的错误才是异常。

Java中使用`Exception`类作为异常祖类，它和`Error`是唯二直接继承`throwable`的类

异常可以被分为4部分来说：
1. 定义异常类
2. 抛出异常类
3. 异常类的传递规则
4. 处理异常

## 定义异常类
继承`Exception`
```java
class CupTooSmallException extends Exception{
    public CupTooSmallException(String message){
        super(message);
    }
}

class CupTooBigException extends Exception{
    public CupTooBigException(String message){
        super(message);
    }
}
```

## 抛出异常类
```java
public class Cup {
    private int size;

    public void setSize(int size) throws CupTooSmallException,CupTooBigException{
        if(size < 100) throw new CupTooSmallException("杯子尺寸是" + size + ",被子太小啦！");
        if(size > 9900) throw new CupTooBigException("杯子尺寸是" + size + ",被子太大啦！");
        this.size = size;
    }
}
```

## 传递规则
从抛出错误的类开始，如果中间没有被`try-catch`捕获，则会一直向上级传递，直到被`java`平台抛出

## 处理
- `try-catch`
- `try-catch-finally`
- `try-finally` 注意，这个不会捕获错误，错误会继续传递

```java
package com.company;

import com.java123.*;

public class Main {
    public static void main(String[] args) throws Exception {
        try {
            Cup cup = new Cup();
            cup.setSize(12220);
        } catch (CupTooSmallException e) {
            System.out.println("成功捕捉到CupTooSmallException错误，提示信息：");
            System.out.println(e.getMessage());
        } catch (CupTooBigException e) {
            System.out.println("成功捕捉到CupTooBigException错误，提示信息：");
            System.out.println(e.getMessage());
        } finally {
            System.out.println("错误处理完成！");
        }
    }
}
```

# 异常的类型
```
- throwable
    - Exception
        - RunTimeException
            - NullPointerException
            - IndexOutOfBoundsException
            - SecurityException
            - IllegalArgumentException
                - NumberFormatException
    - Error
```

- 如果是`RunTimeException`,Java那么允许开发者不做处理，原因是因为这类报错太频繁了
- `Error`也允许不做处理，原因是因为这类错误通常意味着极为严重的，通过`catch`解决不了的问题